### ISSUE TITLE
UpdateAsync Doesn't update custom fields

### ISSUE THREAD

**Issue by matt-shepherd** [tracker086/DocumentDB.AspNet.Identity#13]

**Comment by RoryMcCrossan** [comment]
I note that this is closed, however I am currently experiencing the same issue with this code:

    using (var userManager = HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>())
    {
        var user = await userManager.FindByIdAsync(User.Identity.GetUserId());
        user.Active = false;
        var result = await userManager.UpdateAsync(user);

        if (result.Succeeded) // always true, yet the update is not persisted to the DocumentDb
            return Request.CreateResponse(HttpStatusCode.OK);
        else
            return ErrorResponse(HttpStatusCode.BadRequest, String.Join(", ", result.Errors));
    }

I have ensured that the latest version is used using Update-Package DocumentDB.AspNet.Identity and still have the same problem.

Was a specific fix implemented for this issue?
