### ISSUE TITLE
Method not found: System.Linq.IOrderedQueryable when using version 1.8.0 of the Microsoft.Azure.DocumentDb SDK

### ISSUE THREAD

**Issue by jstawski** [tracker086/DocumentDB.AspNet.Identity#21]
We have upgraded our DocumentDB sdk to version 1.8 and now we get 
Method not found: 'System.Linq.IOrderedQueryable`1<!!0> Microsoft.Azure.Documents.Linq.DocumentQueryable.CreateDocumentQuery(Microsoft.Azure.Documents.Client.DocumentClient, System.String, Microsoft.Azure.Documents.Client.FeedOptions, System.Object)' while instantiating a new UserStore.

Reverting back to 1.7.1 solves the issue.

**Comment by dmitrynovik** [comment]
I am having the same issue

**Comment by jstawski** [comment]
@dmitrynovik "you" as in me or as in the people behind the project?

**Comment by dmitrynovik** [comment]
People behind the project :) It's an one-liner, I've submitted the pull request a few weeks ago but there was no response ...

**Comment by dmitrynovik** [comment]
Eventually I've just cloned the code and I use it as sources, not nuget packages. Two small classes anyway. It's a pity the guys are not responsive.

**Comment by tracker086** [comment]
You're totally right. I apologize for the delay. I've merged the PR, and I'm going to update the NuGet package. Thank you very much for letting me know.

**Comment by tracker086** [comment]
I've updated the Nuget package too. Please let me know if I can do anything else.

**Comment by jstawski** [comment]
@tracker086 thank you, we are giving this a trial as we speak
